spring:
  application:
    name: ffs-task
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true # Format SQL for readability
        # use_sql_comments: true # Optional: Adds comments in SQL queries for clarity
        # generate_statistics: true # Optional: Logs Hibernate statistics
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true

logging:
  level:
    org.hibernate.SQL: debug # Logs the SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: trace # Logs the SQL parameters
    org.springframework.web: debug
    com.joe.abelaziz: debug
