CREATE TABLE authors (
  author_id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(200)
);

CREATE TABLE books (
  book_id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(200),
  type ENUM('SCIENCE', 'HISTORY', 'FICTION'),
  author_id BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (author_id) REFERENCES authors(author_id)
);